services:
  dev:
    container_name: M-league.dev
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: '16gb'
    ports:
      - 8501:8501
    working_dir: /workspace
    volumes:
      - type: bind
        source: $PWD
        target: /workspace
    tty: true
volumes:
  venv:
